package it.polimi.ingsw.model;

import it.polimi.ingsw.model.Consequence.*;

/**
 * the handler for the consequences generated by some action, it manages the different consequence
 */
public interface GameConsequenceHandler {


    void receiveConsequence(Consequence consequence);


    void doConsequence(VictoryConsequence consequence);

    void doConsequence(BlockConsequence consequence);

    void doConsequence(NoConsequence consequence);

    void doConsequence(DestroyTowersConsequence consequence);


}
